//! Builds `extras`, the manifests Luthier carries, into the binary.
//!
//! They are `bench/` at the root of this repository, listed by the same
//! `manifest_files` the index builder walks any registry tree with, and
//! written to `$OUT_DIR/extras.rs` as `include_str!`s that
//! `registry/builtin.rs` reads. Each binary therefore reads exactly the
//! manifests it was released with, and nothing has to be fetched for them.

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
  let crate_dir = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("set by cargo"));
  let bench = crate_dir
    .join("../../bench")
    .canonicalize()
    .expect("bench/ is at the root of the workspace");
  // A directory is scanned whole for changes, so a manifest added, edited
  // or removed rebuilds this.
  println!("cargo:rerun-if-changed={}", bench.display());

  let manifests = luthier_manifest::manifest_files(&bench).expect("bench/ can be listed");
  let mut out = String::from(
    "/// Every manifest in `bench/`, as (path within it, contents). Generated by build.rs.\n\
     pub static MANIFESTS: &[(&str, &str)] = &[\n",
  );
  for path in &manifests {
    let relative = path
      .strip_prefix(&bench)
      .expect("listed beneath bench/")
      .to_str()
      .expect("manifest paths are UTF-8");
    let absolute = path.to_str().expect("manifest paths are UTF-8");
    writeln!(out, "  ({relative:?}, include_str!({absolute:?})),").unwrap();
  }
  out.push_str("];\n\n");

  let engines = bench.join(luthier_manifest::ENGINES_FILE);
  out.push_str("/// `bench/engines.toml`, if there is one. Generated by build.rs.\n");
  // A link is refused, as `manifest_files` skips one: nothing outside
  // bench/ is built into the binary.
  let link = std::fs::symlink_metadata(&engines).is_ok_and(|meta| meta.file_type().is_symlink());
  assert!(!link, "bench/engines.toml must be a file, not a link");
  if engines.is_file() {
    let absolute = engines.to_str().expect("manifest paths are UTF-8");
    writeln!(
      out,
      "pub static ENGINES: Option<&str> = Some(include_str!({absolute:?}));"
    )
    .unwrap();
  } else {
    out.push_str("pub static ENGINES: Option<&str> = None;\n");
  }

  let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("set by cargo"));
  std::fs::write(out_dir.join("extras.rs"), out).expect("OUT_DIR is writable");
}
